baseURL = "https://whs.hk/"
languageCode = "en-us"
title = "Wong Heung Sang"
theme = "mainroad"

[Params]
  copyright = "WHS"
  post_meta = ["date"]

[Params.sidebar]
  home = "right"
  list = "left"
  single = false
  widgets = ["social"]

[Params.widgets.social]
  linkedin = "henry-w-250b64211"
  github = "whs-dot-hk"
